name: Bug Report
description: File a bug report.
title: '[Bug]: '
labels:
- bug
assignees:
- xBourner
body:
- type: markdown
  attributes:
    value: Thanks for taking the time to fill out this bug report!
- type: textarea
  id: what-happened
  attributes:
    label: What happened?
    description: Please tell me exactly what happened while using the card. The more
      detailed, the better.
    placeholder: Tell us what you see!
  validations:
    required: true
- type: textarea
  id: to-reproduce
  attributes:
    label: 'To Reproduce:'
    placeholder: Steps to reproduce the behavior
  validations:
    required: true
- type: textarea
  id: screenshots
  attributes:
    label: Screenshots
    placeholder: If applicable, add screenshots to help explain your problem.
- type: dropdown
  id: ha_version
  attributes:
    label: HA Version
    description: What version of HA are you running? Please update version if you
      don't see your running verision in this list.
    options:
    - 2025.10.3
    - 2025.10.2
    - 2025.10.1
    - 2025.10.0b7
    - 2025.10.0b6
    - 2025.10.0b5
    - 2025.10.0b4
    - 2025.10.0b3
    - 2025.10.0b2
    - 2025.10.0b1
    - 2025.10.0b0
    - 2025.10.0
    - 2025.9.4
    - 2025.9.3
    - 2025.9.2
    - 2025.9.1
    - 2025.9.0b6
    - 2025.9.0b5
    - 2025.9.0b4
    - 2025.9.0b3
    - 2025.9.0b2
    - 2025.9.0b1
    - 2025.9.0b0
    - 2025.9.0
    - 2025.8.3
    - 2025.8.2
    - 2025.8.1
    - 2025.8.0b5
    - 2025.8.0b4
    - 2025.8.0b3
    - 2025.8.0b2
    - 2025.8.0b1
    - 2025.8.0b0
    - 2025.8.0
    default: 0
  validations:
    required: true
- type: dropdown
  id: card_version
  attributes:
    label: Card Version
    description: What version of the card are you running?
    options:
    - v1.0.6-beta
    - v1.0.5
    - v1.0.4
    - v1.0.3
    - v1.0.2-beta
    - v1.0.2
    - v1.0.1
    - v1.0
    - v0.6
    - v0.5.5_beta
    - v0.5.4
    - v0.5.3
    - v0.5.2
    - v0.5.1
    - v0.5.0
    - v0.4.3
    - v0.4.2
    - v0.4.1
    - v0.4.0
    - v0.3.1
    - v0.3.0
    - v0.2.0
    - v0.1.9
    - v0.1.8
    - v0.1.7
    - v0.1.6
    - v0.1.5
    - v0.1.4
    - v0.1.3
    - v0.1.2
    - v0.1.1
    - v0.1.0
    - v0.0.11
    - v0.0.10
    - v0.0.9
    - v0.0.8
    - v0.0.7
    - v0.0.6
    - v0.0.5
    - v0.0.4
    - v0.0.3
    - v0.0.2
    - v0.0.1
    default: 0
  validations:
    required: true
- type: dropdown
  id: browsers
  attributes:
    label: What browsers are you seeing the problem on?
    description: Browser/App
    multiple: true
    options:
    - Firefox
    - Chrome
    - Safari
    - Microsoft Edge
    - HA App on Android
    - HA App on iOS
  validations:
    required: true
- type: checkboxes
  id: terms
  attributes:
    label: Agreement
    options:
    - label: I agree that I updated HA and the card to the latest version and deleted
        my cache or reinstalled the HA app before submitting this bug.
      required: true
