export const DEFAULT_ASPECT_RATIO = "16:9";

export type DomainType =
  | "light"
  | "switch"
  | "fan"
  | "climate"
  | "media_player"
  | "lock"
  | "vacuum"
  | "cover"
  | "binary_sensor";

export const SENSOR_DOMAINS = ["sensor"];
export const ALERT_DOMAINS = ["binary_sensor"];
export const COVER_DOMAINS = ["cover"];
export const CLIMATE_DOMAINS = ["climate"];
export const OTHER_DOMAINS = ["camera"];
export const TOGGLE_DOMAINS = [
  "light",
  "switch",
  "fan",
  "media_player",
  "lock",
  "vacuum",
  "cover",
  "script",
  "scene",
];

export const DEVICE_CLASSES = {
  sensor: ["temperature", "humidity"],
  binary_sensor: ["motion", "window"],
  cover: ["garage"],
};

import {
  mdiAlarmLight,
  mdiAlarmLightOff,
  mdiBellRing,
  mdiBellOff,
  mdiLockOpen,
  mdiLock,
  mdiLightbulb,
  mdiLightbulbOff,
  mdiCast,
  mdiCastOff,
  mdiThermostat,
  mdiThermostatCog,
  mdiAirHumidifier,
  mdiAirHumidifierOff,
  mdiToggleSwitch,
  mdiToggleSwitchOff,
  mdiPowerPlug,
  mdiPowerPlugOff,
  mdiRobotVacuum,
  mdiRobotVacuumOff,
  mdiRobotMower,
  mdiFan,
  mdiFanOff,
  mdiGarageOpen,
  mdiGarage,
  mdiDoorOpen,
  mdiDoorClosed,
  mdiGateOpen,
  mdiGate,
  mdiBlindsOpen,
  mdiBlinds,
  mdiCurtains,
  mdiCurtainsClosed,
  mdiValveOpen,
  mdiValveClosed,
  mdiAwningOutline,
  mdiWindowShutterOpen,
  mdiWindowShutter,
  mdiRollerShade,
  mdiRollerShadeClosed,
  mdiWindowOpen,
  mdiWindowClosed,
  mdiPowerOff,
  mdiMotionSensor,
  mdiMotionSensorOff,
  mdiWaterAlert,
  mdiWaterOff,
  mdiHomeOutline,
  mdiHomeExportOutline,
  mdiSeat,
  mdiSeatOutline,
  mdiVibrate,
  mdiVibrateOff,
  mdiShieldLockOpen,
  mdiShieldLock,
  mdiAlertCircleOutline,
  mdiAlertCircleCheckOutline,
  mdiSmokeDetectorOutline,
  mdiSmokeDetectorOffOutline,
  mdiPlay,
  mdiPause,
  mdiPower,
  mdiBatteryAlert,
  mdiBattery,
  mdiBatteryCharging,
  mdiBatteryCheck,
  mdiGasStationOutline,
  mdiGasStationOffOutline,
  mdiMoleculeCo,
  mdiSnowflake,
  mdiSnowflakeOff,
  mdiWeatherSunny,
  mdiWeatherSunnyOff,
  mdiConnection,
  mdiShieldAlertOutline,
  mdiShieldCheckOutline,
  mdiVolumeHigh,
  mdiVolumeOff,
  mdiAutorenew,
  mdiAutorenewOff,
  mdiShieldHome,
  mdiLightbulbOutline,
  mdiLightbulbOffOutline,
  mdiCar,
  mdiCarOff,
  mdiAccount,
  mdiAccountOff,
  mdiValve,
  mdiWaterBoiler,
  mdiWaterPumpOff,
  mdiRemote,
  mdiRemoteOff,
  mdiAirFilter,
  mdiCamera,
  mdiCameraOff,
  mdiCalendar,
  mdiCalendarRemove,
  mdiMovie,
  mdiMovieOff,
  mdiBell,
  mdiGauge,
  mdiScriptText,
  mdiTagMultiple,
  mdiFormatListBulleted,
  mdiRobot,
  mdiRobotOff,
  mdiGestureTapButton,
  mdiNumeric,
  mdiCommentMultiple,
  mdiSatelliteVariant,
  mdiCounter,
  mdiCalendarStar,
  mdiGoogleCirclesCommunities,
  mdiImage,
  mdiImageOff,
  mdiImageFilterCenterFocus,
  mdiCalendarClock,
  mdiTextBox,
  mdiRecordRec,
  mdiRecord,
  mdiWeatherNight,
  mdiClockOutline,
  mdiClockRemove,
  mdiTimerOutline,
  mdiTimerOff,
  mdiCheckCircleOutline,
  mdiCheckboxBlankCircleOutline,
  mdiMicrophone,
  mdiMicrophoneOff,
  mdiWeatherPartlyCloudy,
  mdiMapMarker,
  mdiMapMarkerOff,
} from "@mdi/js";

export const DOMAIN_ICONS = {
  alarm_control_panel: { on: mdiAlarmLight, off: mdiAlarmLightOff },
  siren: { on: mdiBellRing, off: mdiBellOff },
  lock: { on: mdiLockOpen, off: mdiLock },
  light: { on: mdiLightbulb, off: mdiLightbulbOff },
  media_player: { on: mdiCast, off: mdiCastOff },
  climate: { on: mdiThermostat, off: mdiThermostatCog },
  humidifier: { on: mdiAirHumidifier, off: mdiAirHumidifierOff },
  switch: {
    on: mdiToggleSwitch,
    off: mdiToggleSwitchOff,
    switch: { on: mdiToggleSwitch, off: mdiToggleSwitchOff },
    outlet: { on: mdiPowerPlug, off: mdiPowerPlugOff },
  },
  vacuum: { on: mdiRobotVacuum, off: mdiRobotVacuumOff },
  lawn_mower: { on: mdiRobotMower, off: mdiRobotMower },
  fan: { on: mdiFan, off: mdiFanOff },

  cover: {
    on: mdiGarageOpen,
    off: mdiGarage,
    garage: { on: mdiGarageOpen, off: mdiGarage },
    door: { on: mdiDoorOpen, off: mdiDoorClosed },
    gate: { on: mdiGateOpen, off: mdiGate },
    blind: { on: mdiBlindsOpen, off: mdiBlinds },
    curtain: { on: mdiCurtains, off: mdiCurtainsClosed },
    damper: { on: mdiValveOpen, off: mdiValveClosed },
    awning: { on: mdiAwningOutline, off: mdiAwningOutline },
    shutter: { on: mdiWindowShutterOpen, off: mdiWindowShutter },
    shade: { on: mdiRollerShade, off: mdiRollerShadeClosed },
    window: { on: mdiWindowOpen, off: mdiWindowClosed },
  },
  binary_sensor: {
    on: mdiPowerOff,
    off: mdiPowerOff,
    motion: { on: mdiMotionSensor, off: mdiMotionSensorOff },
    moisture: { on: mdiWaterAlert, off: mdiWaterOff },
    window: { on: mdiWindowOpen, off: mdiWindowClosed },
    door: { on: mdiDoorOpen, off: mdiDoorClosed },
    lock: { on: mdiLockOpen, off: mdiLock },
    presence: { on: mdiHomeOutline, off: mdiHomeExportOutline },
    occupancy: { on: mdiSeat, off: mdiSeatOutline },
    vibration: { on: mdiVibrate, off: mdiVibrateOff },
    opening: { on: mdiShieldLockOpen, off: mdiShieldLock },
    garage_door: { on: mdiGarageOpen, off: mdiGarage },
    problem: {
      on: mdiAlertCircleOutline,
      off: mdiAlertCircleCheckOutline,
    },
    smoke: {
      on: mdiSmokeDetectorOutline,
      off: mdiSmokeDetectorOffOutline,
    },
    running: { on: mdiPlay, off: mdiPause },
    plug: { on: mdiPowerPlug, off: mdiPowerPlugOff },
    power: { on: mdiPower, off: mdiPowerOff },
    battery: { on: mdiBatteryAlert, off: mdiBattery },
    battery_charging: { on: mdiBatteryCharging, off: mdiBatteryCheck },
    gas: { on: mdiGasStationOutline, off: mdiGasStationOffOutline },
    carbon_monoxide: { on: mdiMoleculeCo, off: mdiMoleculeCo },
    cold: { on: mdiSnowflake, off: mdiSnowflakeOff },
    heat: { on: mdiWeatherSunny, off: mdiWeatherSunnyOff },
    connectivity: { on: mdiConnection, off: mdiConnection },
    safety: { on: mdiShieldAlertOutline, off: mdiShieldCheckOutline },
    sound: { on: mdiVolumeHigh, off: mdiVolumeOff },
    update: { on: mdiAutorenew, off: mdiAutorenewOff },
    tamper: { on: mdiShieldHome, off: mdiShieldHome },
    light: { on: mdiLightbulbOutline, off: mdiLightbulbOffOutline },
    moving: { on: mdiCar, off: mdiCarOff },
  },
  person: { on: mdiAccount, off: mdiAccountOff },
  device_tracker: { on: mdiAccount, off: mdiAccountOff },
  valve: { on: mdiValve, off: mdiValveClosed },
  water_heater: { on: mdiWaterBoiler, off: mdiWaterPumpOff },
  remote: { on: mdiRemote, off: mdiRemoteOff },
  update: { on: mdiAutorenew, off: mdiAutorenewOff },
  air_quality: { on: mdiAirFilter, off: mdiAirFilter },
  camera: { on: mdiCamera, off: mdiCameraOff },
  calendar: { on: mdiCalendar, off: mdiCalendarRemove },
  scene: { on: mdiMovie, off: mdiMovieOff },
  notifications: { on: mdiBell, off: mdiBellOff },
  sensor: { on: mdiGauge, off: mdiGauge },
  script: { on: mdiScriptText, off: mdiScriptText },
  tags: { on: mdiTagMultiple, off: mdiTagMultiple },
  select: { on: mdiFormatListBulleted, off: mdiFormatListBulleted },
  automation: { on: mdiRobot, off: mdiRobotOff },
  button: { on: mdiGestureTapButton, off: mdiGestureTapButton },
  number: { on: mdiNumeric, off: mdiNumeric },
  conversation: { on: mdiCommentMultiple, off: mdiCommentMultiple },
  assist_satellite: {
    on: mdiSatelliteVariant,
    off: mdiSatelliteVariant,
  },
  counter: { on: mdiCounter, off: mdiCounter },
  event: { on: mdiCalendarStar, off: mdiCalendarStar },
  group: {
    on: mdiGoogleCirclesCommunities,
    off: mdiGoogleCirclesCommunities,
  },
  image: { on: mdiImage, off: mdiImageOff },
  image_processing: {
    on: mdiImageFilterCenterFocus,
    off: mdiImageFilterCenterFocus,
  },
  input_boolean: { on: mdiToggleSwitch, off: mdiToggleSwitchOff },
  input_datetime: { on: mdiCalendarClock, off: mdiCalendarClock },
  input_number: { on: mdiNumeric, off: mdiNumeric },
  input_select: {
    on: mdiFormatListBulleted,
    off: mdiFormatListBulleted,
  },
  input_text: { on: mdiTextBox, off: mdiTextBox },
  stt: { on: mdiRecordRec, off: mdiRecord },
  sun: { on: mdiWeatherSunny, off: mdiWeatherNight },
  text: { on: mdiTextBox, off: mdiTextBox },
  date: { on: mdiCalendar, off: mdiCalendarRemove },
  datetime: { on: mdiCalendarClock, off: mdiCalendarClock },
  time: { on: mdiClockOutline, off: mdiClockRemove },
  timer: { on: mdiTimerOutline, off: mdiTimerOff },
  todo: {
    on: mdiCheckCircleOutline,
    off: mdiCheckboxBlankCircleOutline,
  },
  tts: { on: mdiVolumeHigh, off: mdiVolumeOff },
  wake_word: { on: mdiMicrophone, off: mdiMicrophoneOff },
  weather: { on: mdiWeatherPartlyCloudy, off: mdiWeatherNight },
  zone: { on: mdiMapMarker, off: mdiMapMarkerOff },
  geo_location: { on: mdiMapMarker, off: mdiMapMarkerOff },
};

export interface CustomizationConfig {
  type: string;
  css?: string | Record<string, any>;
  icon_css?: string | Record<string, any>;
  _parsedCss?: Record<string, string>;
  _parsedIconCss?: Record<string, string>;
  styles?: Record<string, any>;
}
